[package]
name = "filecoin-proofs-api"
version = "0.1.0"
authors = ["dignifiedquire <me@dignifiedquire.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.26"

[dependencies.filecoin-proofs-v1]
version = "1.0.0-alpha.0"
path = "../rust-proofs/filecoin-proofs"
package = "filecoin-proofs"
